server:
  port: 8080
spring:
  application:
    name: zuul-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  sensitive-headers:
  routes:
    games-api:
      path: /api/**
      serviceId: games-service
    games-frontend:
      path: /**
      serviceId: games-frontend

